### PR TITLE
Add bisectCenter.

### PR DESCRIPTION
**Pull request by mbostock**
Looks like we forgot to add the identity bisector for *bisector*.center. #138

### CODE REVIEW

**Comment by mbostock** [comment]
Related question: because *hi* defaults to *array*.length, this doesn’t do what I want (return the index of the closest value) when *value* is greater than *array*[*array*.length - 1]:

```js
const i = d3.bisectCenter(array, value);
```

Instead I need to say:

```js
const i = d3.bisectCente(array, value, 0, array.length - 1);
```

I wonder if this is a mistake and we should instead default *hi* to *array*.length - 1 in the case of *bisector*.center?

**Comment by mbostock** [comment]
Okay, given that the documented behavior is “finds the index of the closest value”, this is clearly a bug. I’ve fixed the bug and added a test.

**Review by Fil — APPROVED** [review]
By coercing the values to numbers we now have:

> d3.bisectCenter(["A", "B", "C", "D"], "C"); // 0

where the previous version was giving 2.

This is not what I expect from the documentation:
> This expects that the bisector’s associated accessor returns a quantitative value, or that the bisector’s associated comparator returns a signed distance; **otherwise, this method is equivalent to *bisector*.left.**

> d3.bisectLeft(["A", "B", "C", "D"], "C"); // 2
> d3.bisector(d3.ascending).center(["A", "B", "C", "D"], "C"); // 2

If we keep the code as is (which makes sense), then the documentation for bisectCenter should be expanded a bit 
> [*bisector*.center](#bisector_center) with a numeric substraction comparator

(or something in better English)

**Comment by Fil** [comment]
https://observablehq.com/@d3/d3-bisect will need a small update

**Comment by mbostock** [comment]
I’ve updated the documentation to say that d3.bisectCenter requires an array of numbers (as opposed to ordinal values).

**Review by Fil — APPROVED** [review]

**Pull request merged**
