### PR TITLE
Implement Kahan summation.

### LINKED ISSUE #33: Use Kahan summation algorithm?
h/t https://github.com/simple-statistics/simple-statistics/blob/master/src/sum.js

### PR DESCRIPTION
**Pull request by mbostock**
Fixes #33. Not sure if this is worth doing, though. I’d like some examples.

### CODE REVIEW

**Comment by Fil** [comment]
An example here https://observablehq.com/@fil/kahan-summation

**Comment by mbostock** [comment]
Some precedent in numpy and Julia suggests that pairwise summation may be preferable (though unclear if using iterables will be performant):

https://en.m.wikipedia.org/wiki/Pairwise_summation

**Comment by Fil** [comment]
I don't think pairwise summation solves the `1.0 + eps - eps` case.

**Comment by Fil** [comment]
rebased in #149

**Pull request closed without merging**
